## 使用druid配置数据源
spring:
  application:
    name: basic-demo-test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: Smart_888
      url: jdbc:mysql://192.168.0.55:8635/erp_basic?characterEncoding=UTF-8
      max-active: 20
      validation-query: SELECT 1 FROM DUAL
      initial-size: 10
      max-wait: 60000

## eureka server 地址， 根据实际情况设置eureka server地址
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.100:8761/eureka,http://192.168.0.171:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 49.4.2.78
    instance-id: 49.4.2.78:8791